# Generated by Django 5.0.6 on 2024-05-28 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('date_of_employment', models.DateField()),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('chief', models.ForeignKey(blank=True, help_text='The chief of the employee. Can be null if not assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree.employee')),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['position'], name='tree_employ_positio_01688f_idx'), models.Index(fields=['email'], name='tree_employ_email_6e5458_idx')],
            },
        ),
    ]
